name: scribe
description: Logging backends for logging package.
version: 0.0.1
author: stable/kernel <jobs@stablekernel.com>
homepage: http://www.stablekernel.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  logging: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
