name: scribe
description: Logging backends for logging package.
version: 0.1.0+1
author: stable|kernel <http://stablekernel.com>
homepage: https://github.com/stablekernel
documentation:

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  logging: ">=0.11.2 <0.12.0"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
